name: ${project.name}
main: com.github.ucchyocean.lc.LunaChat
version: ${project.version}
authors: [ucchy, YukiLeafX, LazyGon]
description: ${project.description}
softdepend: [Vault, dynmap, HawkEye, Multiverse-Core, mcMMO, Prism]

commands:
  lunachat:
    description: lunachat user command
    aliases: [ch, lc]
    usage: |
           /<command> join (channel) - Join the channel.
           /<command> leave - Leave a participating channel.
           /<command> list - Display a list of channels.
           /<command> invite (name) [force] - Invite the specified person to join the channel chat.
           /<command> accept - Accept the invitation and enter the channel chat.
           /<command> deny - reject the invitation.
           /<command> kick (name) [channel] - Kick the specified person from channel chat.
           /<command> ban (name) [channel] - BAN the specified person from channel chat.
           /<command> ban (name) [minutes] - BAN the specified person for the specified number of minutes.
           /<command> pardon (name) [channel] - removes the ban for the specified person.
           /<command> mute (name) [channel] - Mute the specified person from channel chat.
           /<command> mute (name) [minutes] - Mute the specified person for the specified number of minutes.
           /<command> unmute (name) [channel] - Unmute the specified person.
           /<command> hide (channel) - Hide the content of the specified channel.
           /<command> hide channel (channel) - Hide the content of the specified channel.
           /<command> hide (player) - Hides what the specified player says.
           /<command> hide player (player) - hides what the specified player says.
           /<command> unhide (channel) - Unhides the content of the specified channel.
           /<command> unhide channel (channel) - Unhides the content of the specified channel.
           /<command> unhide (player) - Returns the specified player's comment from hidden to visible.
           /<command> unhide player (player) - Returns the speech of the specified player from hidden to visible.
           /<command> info [channel] - Display channel information.
           /<command> log [channel] [key=value ...] - Display the channel log.
           /<command> create (channel) - create a channel.
           /<command> remove [channel] - remove a channel.
           /<command> format [channel] (format ...) - sets the message format for the channel.
           /<command> moderator [channel] (player ...) - Set the moderator for the channel to the specified player.
           /<command> dictionary (add (word) (value)|remove (word)) - Adds a new word to the Japanize conversion dictionary or deletes the specified word.
           /<command> option (key=value ...) - Set options for the channel.
           /<command> template (number) (template ...) - Register a message format template.
           /<command> check - List channels without moderators.
           /<command> check remove - removes all channels listed by /<command> check.
           /<command> set default (player) [channel] - Sets the channel to which the specified player speaks to the specified channel.
           /<command> reload - reload config.yml.
           /<command> help [user|mod|admin] [page] - Display help.
  tell:
    description: 1: 1 chat send command
    aliases: [msg, message, m, t, w]
    usage: /<command> (name) [message] - Start a 1:1 chat with the specified person.
    permission: lunachat.message
    permission-message: Cannot execute because there is no permission "<permission>".
  reply:
    description: 1: 1 chat reply command
    aliases: [r]
    usage: /<command> [message] - Reply to incoming 1:1 chat.
    permission: lunachat.reply
    permission-message: Cannot execute because there is no permission "<permission>".
  lcjapanize:
    description: lunaize japanize on/off setting command
    aliases: [japanize, jp]
    usage: |
           /<command> on|off-Turn on/off the Japanize conversion of your chat.
           /<command> (player) (on|off)-Turn on/off the Japanize conversion of other player's chat.
    permission: lunachat.japanize
    permission-message: You don't have the permission "<permission>".

permissions:
  lunachat.join:
    description: Permission to use the join command
    default: true
  lunachat.leave:
    description: Permission to use leave command
    default: true
  lunachat.list:
    description: List command usage privilege
    default: true
  lunachat.invite:
    description: invite command permission
    default: true
  lunachat.accept:
    description: Authorization to use the accept command
    default: true
  lunachat.deny:
    description: Permission to use the deny command
    default: true
  lunachat.kick:
    description: Permission to use the kick command
    default: true
  lunachat.ban:
    description: ban command usage privilege
    default: true
  lunachat.pardon:
    description: Pardon command usage privilege
    default: true
  lunachat.mute:
    description: Authorization to use the mute command
    default: true
  lunachat.unmute:
    description: Permission to use the unmute command
    default: true
  lunachat.hide:
    description: Permission to use the hide command
    default: true
  lunachat.unhide:
    description: Usage rights for the unhide command
    default: true
  lunachat.info:
    description: info command usage privilege
    default: true
  lunachat.log:
    description: Authorization to use the log command
    default: true
  lunachat.create:
    description: Authorization to use the create command
    default: true
  lunachat.remove:
    description: Permission to use the remove command
    default: true
  lunachat.format:
    description: Permission to use the format command
    default: true
  lunachat.moderator:
    description: Permission to use the moderator command
    default: true
  lunachat.option:
    description: Option command authorization
    default: true
  lunachat.message:
    description: Permission to use the message command
    default: true
  lunachat.reply:
    description: Permission to use the reply command
    default: true
  lunachat.help:
    description: permission to use help command
    default: true
  lunachat.japanize:
    description: Authorization to use japanize on/off setting command of lunachat
    default: true
  lunachat.allowcc:
    description: Right to use color code in chat
    default: true
  lunachat.*:
    children:
      lunachat.join: true
      lunachat.leave: true
      lunachat.list: true
      lunachat.invite: true
      lunachat.accept: true
      lunachat.deny: true
      lunachat.kick: true
      lunachat.ban: true
      lunachat.pardon: true
      lunachat.mute: true
      lunachat.unmute: true
      lunachat.hide: true
      lunachat.unhide: true
      lunachat.info: true
      lunachat.log: true
      lunachat.create: true
      lunachat.remove: true
      lunachat.format: true
      lunachat.moderator: true
      lunachat.option: true
      lunachat.message: true
      lunachat.reply: true
      lunachat.help: true
      lunachat.japanize: true
      lunachat.allowcc: true
    description: Permission to use all commands for general users

  lunachat.option.description:
    description: Permission to use the description option setting command
    default: true
  lunachat.option.alias:
    description: alias Right to use option setting command
    default: true
  lunachat.option.color:
    description: color Permission to use the option setting command
    default: true
  lunachat.option.broadcast:
    description: permission to use the broadcast option setting command
    default: op
  lunachat.option.range:
    description: range Permission to use the option setting command
    default: op
  lunachat.option.password:
    description: password Permission to use the option setting command
    default: true
  lunachat.option.visible:
    description: visible Right to use option setting command
    default: true
  lunachat.option.allowcc:
    description: permission to use the allowcc option setting command
    default: true
  lunachat.option.japanize:
    description: Authorization to use the japanize option setting command
    default: true
  lunachat.option.*:
    children:
      lunachat.option.description: true
      lunachat.option.alias: true
      lunachat.option.color: true
      lunachat.option.broadcast: true
      lunachat.option.range: true
      lunachat.option.password: true
      lunachat.option.visible: true
      lunachat.option.allowcc: true
      lunachat.option.japanize: true
    description: Permission to use all commands in option settings

  lunachat-admin.mod-all-channels:
    description: Moderator authority for all channels
    default: op
  lunachat-admin.listen-all-channels:
    description: Chat display permission for all channels
    default: op
  lunachat-admin.template:
    description: Authorization to use the template command
    default: op
  lunachat-admin.dictionary:
    description: Authorization to use the dictionary command
    default: op
  lunachat-admin.check:
    description: Permission to use the check command
    default: op
  lunachat-admin.set:
    description: Permission to use the set command
    default: op
  lunachat-admin.reload:
    permission to use the description: reload command
    default: op
  lunachat-admin.japanize-other:
    description: Authorization to use the japanize on/off setting command of others
    default: op
  lunachat-admin.force-invite:
    description: Authorization to use forced entry command
    default: op
  lunachat-admin.*:
    children:
      lunachat-admin.mod-all-channels: true
      lunachat-admin.listen-all-channels: true
      lunachat-admin.template: true
      lunachat-admin.dictionary: true
      lunachat-admin.check: true
      lunachat-admin.set: true
      lunachat-admin.reload: true
      lunachat-admin.japanize-other: true
      lunachat-admin.force-invite: true
    description: Permission to use all commands for administrators